force-app/main/default/objects/AmplitudeKey__c/AmplitudeKey__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Amplitude key</label>
</CustomObject>

force-app/main/default/objects/AmplitudeKey__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AmplitudeHelper.cls
public with sharing class AmplitudeHelper {
    
    @AuraEnabled(cacheable=true) 
    public static String getAmplitudeKey(){
        if (AmplitudeKey__c.getValues(UserInfo.getUserId()) != null) {
            return AmplitudeKey__c.getValues(UserInfo.getUserId()).Key__c;
        } else if (AmplitudeKey__c.getValues(UserInfo.getProfileId()) != null) {
            return AmplitudeKey__c.getValues(UserInfo.getProfileId()).Key__c;
        }
        return AmplitudeKey__c.getOrgDefaults().Key__c;
    }    
}