force-app/main/default/objects/ReportingData__c/ReportingData__c.object-meta.xml
<CustomObject>
    <label>Reporting Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReportingData__c/fields/HOT_Request__c.field-meta.xml
<CustomField>
    <fullName>HOT_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>HOT_Request__c</referenceTo>
    <relationshipLabel>Reporting Data</relationshipLabel>
    <relationshipName>Reporting_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HOT_SAReportControllerTest.cls
@isTest
private class HOT_SAReportControllerTest{

	@testSetup static void setup(){

		WorkType workType = HOT_TestDataFactory.createWorkType();
		insert workType;
		HOT_Request__c request = HOT_TestDataFactory.createRequest('Bestilling', workType);
		insert request;
		request.Status__c = 'Godkjent';
		update request;

		HOT_ServiceAppointmentReportController.upsertReportingData(Date.today().addDays(-1), Date.today().addDays(1));
	}

	@isTest static void upsertReportingDataTest() {
        List<ReportingData__c> reportingData=[SELECT Id FROM ReportingData__c];
        System.assertNotEquals(reportingData.size(), 0);
	}

}