force-app/main/default/objects/ReportingData__c/ReportingData__c.object-meta.xml
<CustomObject>
    <label>Reporting Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReportingData__c/fields/CRM_Category__c.field-meta.xml
<CustomField>
    <fullName>CRM_Category__c</fullName>
    <description>Reporting Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Adoption</fullName>
            </value>
            <value>
                <fullName>New Users</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>DIA User Adoption</fullName>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>Video View</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>BTO Transfer</fullName>
            </value>
            <value>
                <fullName>BTO</fullName>
            </value>
            <value>
                <fullName>STO Transfer</fullName>
            </value>
            <value>
                <fullName>TAG External Notification</fullName>
            </value>
            <value>
                <fullName>Chat Threat</fullName>
            </value>
            <value>
                <fullName>Kommunal hurtigtekst</fullName>
            </value>
            <value>
                <fullName>TAG Admin</fullName>
            </value>
            <value>
                <fullName>Besvart med Bob</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Region__c.field-meta.xml
<CustomField>
    <fullName>CRM_Region__c</fullName>
    <description>Users&#39;s region</description>
    <label>Region</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_ActualEndTime__c.field-meta.xml
<CustomField>
    <fullName>HOT_ActualEndTime__c</fullName>
    <label>SA: Actual End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_ActualStartTime__c.field-meta.xml
<CustomField>
    <fullName>HOT_ActualStartTime__c</fullName>
    <label>Actual Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_AssignmentType__c.field-meta.xml
<CustomField>
    <fullName>HOT_AssignmentType__c</fullName>
    <label>Assignment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>HOT_AssignmentType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_DueDate__c.field-meta.xml
<CustomField>
    <fullName>HOT_DueDate__c</fullName>
    <label>SA: Due date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_EarliestStartTime__c.field-meta.xml
<CustomField>
    <fullName>HOT_EarliestStartTime__c</fullName>
    <label>Earliest start time permitted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_IsAcute__c.field-meta.xml
<CustomField>
    <fullName>HOT_IsAcute__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request: Acute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_IsEmployedInterpreter__c.field-meta.xml
<CustomField>
    <fullName>HOT_IsEmployedInterpreter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Employed Interpreter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_IsFreelanceInterpreter__c.field-meta.xml
<CustomField>
    <fullName>HOT_IsFreelanceInterpreter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SA: Freelance Interpreter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_Request__c.field-meta.xml
<CustomField>
    <fullName>HOT_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Request</label>
    <referenceTo>HOT_Request__c</referenceTo>
    <relationshipLabel>Reporting Data</relationshipLabel>
    <relationshipName>Reporting_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_RequestCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>HOT_RequestCreatedDate__c</fullName>
    <label>Request Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_RequestName__c.field-meta.xml
<CustomField>
    <fullName>HOT_RequestName__c</fullName>
    <label>Request: Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_RequestSubject__c.field-meta.xml
<CustomField>
    <fullName>HOT_RequestSubject__c</fullName>
    <label>Request: Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_SchedEndTime__c.field-meta.xml
<CustomField>
    <fullName>HOT_SchedEndTime__c</fullName>
    <label>Scheduled End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_SchedStartTime__c.field-meta.xml
<CustomField>
    <fullName>HOT_SchedStartTime__c</fullName>
    <label>SA: Scheduled Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_ServiceAppointment__c.field-meta.xml
<CustomField>
    <fullName>HOT_ServiceAppointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Reporting Data</relationshipLabel>
    <relationshipName>Reporting_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_ServiceAppointmentCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>HOT_ServiceAppointmentCreatedDate__c</fullName>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_Status__c.field-meta.xml
<CustomField>
    <fullName>HOT_Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/HOT_WorkType__c.field-meta.xml
<CustomField>
    <fullName>HOT_WorkType__c</fullName>
    <label>SA: Work Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HOT_ServiceAppointmentReportController.cls
public with sharing class HOT_ServiceAppointmentReportController {
 

    public static void upsertReportingData(Date periodStart, Date periodEnd) {
        List<ServiceAppointment> serviceAppointments = [SELECT Id, ParentRecordId, HOT_IsEmployedInterpreter__c, HOT_IsReleasedToFreelance__c, WorkType.Name, ServiceTerritory.Name,
                                                               EarliestStartTime, DueDate, SchedStartTime, SchedEndTime, ActualStartTime, ActualEndTime
                                                        FROM ServiceAppointment WHERE LastModifiedDate >= :periodStart AND LastModifiedDate <= :periodEnd];
        
        Map<Id, ServiceAppointment> IdtoSA = new Map<Id, ServiceAppointment>();
        for(ServiceAppointment sa:serviceAppointments){
            IdtoSA.put(sa.Id, sa);
        }

        Map<Id, Id> SAtoWOLI = new Map<Id, Id>();
        for(ServiceAppointment sa:serviceAppointments){
            SAtoWOLI.put(sa.Id, sa.ParentRecordId);
        }
        List<WorkOrderLineItem> workOrderLineItems = [SELECT Id, WorkOrderId FROM WorkOrderLineItem WHERE Id IN :SAtoWOLI.values()];
        Map<Id, Id> WOLItoWO = new Map<Id, Id>();
        for(WorkOrderLineItem woli:workOrderLineItems){
            WOLItoWO.put(woli.Id, woli.WorkOrderId);
        }
        List<WorkOrder> workOrders = [SELECT Id, HOT_Request__c FROM WorkOrder WHERE Id IN :WOLItoWO.values()];
        Map<Id, Id> WOtoRequest = new Map<Id, Id>();
        for(WorkOrder wo:workOrders){
            WOtoRequest.put(wo.Id, wo.HOT_Request__c);
        }
        List<HOT_Request__c> requests = [SELECT Id, AssignmentType__c, IsAcute__c, Status__c        
                                         FROM HOT_Request__c WHERE Id IN :WOtoRequest.values()];
        
        Map<Id, HOT_Request__c> requestMap = new Map<Id, HOT_Request__c>();
        for(HOT_Request__c req:requests){
            requestMap.put(req.Id, req);
        }

        Map<Id, HOT_Request__c> SAIdtoRequest = new Map<Id, HOT_Request__c>();
        for(Id saId:SAtoWOLI.keySet()){
            SAIdtoRequest.put(saId, requestMap.get(WOtoRequest.get(WOLItoWO.get(SAtoWOLI.get(saId)))));
        }
        
        List<ReportingData__c> reportingData = [SELECT Id, HOT_ServiceAppointment__c FROM ReportingData__c WHERE HOT_ServiceAppointment__c IN :SAIdtoRequest.keySet()];
        Map<Id, ReportingData__c> SAIdtoRepData = new Map<Id, ReportingData__c>();
        for(ReportingData__c repData:reportingData){
            SAIdtoRepData.put(repData.HOT_ServiceAppointment__c, repData);
        }
        
        for(ServiceAppointment sa:serviceAppointments){
            if(SAIdtoRepData.containsKey(sa.Id)){
                SAIdtoRepData.put(sa.Id, setFieldValues(SAIdtoRepData.get(sa.Id), IdtoSA.get(sa.Id), SAIdtoRequest.get(sa.Id)));
            }
            else{
                ReportingData__c repData = new ReportingData__c();
                SAIdtoRepData.put(sa.Id, setFieldValues(repData, IdtoSA.get(sa.Id), SAIdtoRequest.get(sa.Id)));
            }
        }
        upsert SAIdtoRepData.values();
    }

    public static ReportingData__c setFieldValues(ReportingData__c repData, ServiceAppointment serviceAppointment, HOT_Request__c request){
        repData.CRM_Category__c = 'Service Appointment';
        repData.HOT_AssignmentType__c = request.AssignmentType__c;
        repData.HOT_IsAcute__c = request.IsAcute__c;
        repData.HOT_IsEmployedInterpreter__c = serviceAppointment.HOT_IsEmployedInterpreter__c;
        repData.HOT_IsFreelanceInterpreter__c = serviceAppointment.HOT_IsReleasedToFreelance__c;
        repData.HOT_ServiceAppointment__c = serviceAppointment.Id;
        repData.HOT_WorkType__c = serviceAppointment.WorkType.Name;
        repData.HOT_Status__c = request.Status__c;
        repData.CRM_Region__c = serviceAppointment.ServiceTerritory.Name;
        repData.HOT_EarliestStartTime__c = serviceAppointment.EarliestStartTime;
        repData.HOT_DueDate__c = serviceAppointment.DueDate;
        repData.HOT_SchedStartTime__c = serviceAppointment.SchedStartTime;
        repData.HOT_SchedEndTime__c = serviceAppointment.SchedEndTime;
        repData.HOT_ActualStartTime__c = serviceAppointment.ActualStartTime;
        repData.HOT_ActualEndTime__c = serviceAppointment.ActualEndTime;
        repData.HOT_RequestCreatedDate__c = request.CreatedDate;
        repData.HOT_RequestName__c = request.Name;
        repData.HOT_RequestSubject__c = request.Subject__c;
        repData.HOT_ServiceAppointmentCreatedDate__c = serviceAppointment.CreatedDate;
        return repData;
    }

}