force-app/main/default/objects/ReportingData__c/ReportingData__c.object-meta.xml
<CustomObject>
    <label>Reporting Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReportingData__c/fields/CRM_Category__c.field-meta.xml
<CustomField>
    <fullName>CRM_Category__c</fullName>
    <description>Reporting Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Adoption</fullName>
            </value>
            <value>
                <fullName>New Users</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>DIA User Adoption</fullName>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>Video View</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>BTO Transfer</fullName>
            </value>
            <value>
                <fullName>BTO</fullName>
            </value>
            <value>
                <fullName>STO Transfer</fullName>
            </value>
            <value>
                <fullName>TAG External Notification</fullName>
            </value>
            <value>
                <fullName>Chat Threat</fullName>
            </value>
            <value>
                <fullName>Kommunal hurtigtekst</fullName>
            </value>
            <value>
                <fullName>TAG Admin</fullName>
            </value>
            <value>
                <fullName>Besvart med Bob</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_NavUnit__c.field-meta.xml
<CustomField>
    <fullName>CRM_NavUnit__c</fullName>
    <label>Nav Unit</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Value__c.field-meta.xml
<CustomField>
    <fullName>CRM_Value__c</fullName>
    <description>Reporting value in integer</description>
    <label>Value</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Week__c.field-meta.xml
<CustomField>
    <fullName>CRM_Week__c</fullName>
    <description>Week number</description>
    <label>Value</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DIA_UserAdoption_Schedule_Test.cls
@IsTest
private class DIA_UserAdoption_Schedule_Test {
    @TestSetup
    private static void makeData(){
        Profile platformProfile=[SELECT Id FROM Profile WHERE Name='Standard Platform User' LIMIT 1];

        User platformUser=new User();
        platformUser.FirstName='Platform';
        platformUser.LastName='Test';
        platformUser.Email='test.platform@nav.no';
        platformUser.UserName='test.platform423_fdsfds@nav.no';
        platformUser.ProfileId=platformProfile.Id;
        platformUser.CRM_Nav_Ident__c='A123456';
        platformUser.Alias='plattest';
        platformUser.TimeZoneSidKey='Europe/Paris';
        platformUser.LocaleSidKey='no_NO';
        platformUser.EmailEncodingKey='ISO-8859-1';
        platformUser.LanguageLocaleKey='no';
        platformUser.CompanyName='Test Unit';
        insert platformUser;
        system.debug(platformUser);
      
    }
    @IsTest
    private static void testScheduleExecute() {
      
        Test.startTest();
        DIA_UserAdoption_Schedule scheduleClass = new DIA_UserAdoption_Schedule();
        String chron = '0 0 23 * * ?';
        System.schedule('Create user adoption job', chron, scheduleClass);
        Test.stopTest();
        System.assertEquals(
            1,
            [SELECT COUNT() FROM CronTrigger WHERE CronJobDetail.Name = 'Create user adoption job'],
            '1 job should be scheduled'
        );
        System.assertEquals(
            1,
            [SELECT COUNT() FROM ReportingData__c WHERE CRM_Category__c='DIA User Adoption' AND CRM_Week__c=1 AND CRM_NavUnit__c='Test Unit' AND CRM_Value__c=1],
            '1 Reporting Data record should be created'
        );
       
    }
}