force-app/main/default/objects/ReportingData__c/ReportingData__c.object-meta.xml
<CustomObject>
    <label>Reporting Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReportingData__c/fields/CRM_Category__c.field-meta.xml
<CustomField>
    <fullName>CRM_Category__c</fullName>
    <description>Reporting Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Adoption</fullName>
            </value>
            <value>
                <fullName>New Users</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>DIA User Adoption</fullName>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>Video View</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>BTO Transfer</fullName>
            </value>
            <value>
                <fullName>BTO</fullName>
            </value>
            <value>
                <fullName>STO Transfer</fullName>
            </value>
            <value>
                <fullName>TAG External Notification</fullName>
            </value>
            <value>
                <fullName>Chat Threat</fullName>
            </value>
            <value>
                <fullName>Kommunal hurtigtekst</fullName>
            </value>
            <value>
                <fullName>TAG Admin</fullName>
            </value>
            <value>
                <fullName>Besvart med Bob</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_NavUnit__c.field-meta.xml
<CustomField>
    <fullName>CRM_NavUnit__c</fullName>
    <label>Nav Unit</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Value__c.field-meta.xml
<CustomField>
    <fullName>CRM_Value__c</fullName>
    <description>Reporting value in integer</description>
    <label>Value</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Week__c.field-meta.xml
<CustomField>
    <fullName>CRM_Week__c</fullName>
    <description>Week number</description>
    <label>Value</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DIA_UserAdoption_Schedule.cls
public with sharing class DIA_UserAdoption_Schedule implements Schedulable {
    
    public void execute(SchedulableContext sc) {
        Integer weekNumber=getWeekNumber();
        //remove data for current week before insterting new data
        DELETE [SELECT Id FROM ReportingData__c WHERE CRM_Category__c='DIA User Adoption' AND CRM_Week__c=:weekNumber];

        List<ReportingData__c> recordsToBeInserted=new List<ReportingData__c>();
        DateTime startOfWeek=Date.Today().AddDays(-1).toStartOfWeek();
        AggregateResult[] users=[SELECT CompanyName, COUNT(Id) numberOfUsers FROM USER WHERE ProfileId in('00e7U000000cWBPQA2','00e7U000000cWBUQA2')  AND LastLoginDate>=:startOfWeek GROUP BY CompanyName];
        if(Test.isRunningTest()){
            User platformUser=[SELECT Id FROM User WHERE UserName='test.platform423_fdsfds@nav.no' LIMIT 1];
            //aggregate result for test purpose
            users=[SELECT CompanyName, COUNT(Name) numberOfUsers FROM USER WHERE UserName='test.platform423_fdsfds@nav.no' GROUP BY CompanyName];
        }
        for(AggregateResult ar:users){
            ReportingData__c usersPerUnit=new ReportingData__c();
            usersPerUnit.CRM_Category__c='DIA User Adoption';
            usersPerUnit.CRM_Week__c=weekNumber;
            usersPerUnit.CRM_NavUnit__c=(String)ar.get('CompanyName');
            usersPerUnit.CRM_Value__c=(Integer)ar.get('numberOfUsers');
            recordsToBeInserted.add(usersPerUnit);
        }
        insert recordsToBeInserted;
    } 

    public Integer getWeekNumber(){
        Integer weekNumber=Integer.valueOf(DateTime.newInstanceGmt(Date.Today().AddDays(-1).toStartOfWeek(), Time.NewInstance(12,0,0,0)).format('w'))-1;
        if(Test.isRunningTest()){
            weekNumber=1;
        }
        return weekNumber;
    }

 

}