force-app/main/default/objects/ReportingData__c/ReportingData__c.object-meta.xml
<CustomObject>
    <label>Reporting Data</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reporting Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReportingData__c/fields/CRM_Category__c.field-meta.xml
<CustomField>
    <fullName>CRM_Category__c</fullName>
    <description>Reporting Category</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Adoption</fullName>
            </value>
            <value>
                <fullName>New Users</fullName>
            </value>
            <value>
                <fullName>Service Appointment</fullName>
            </value>
            <value>
                <fullName>DIA User Adoption</fullName>
            </value>
            <value>
                <fullName>STO</fullName>
            </value>
            <value>
                <fullName>Video View</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>BTO Transfer</fullName>
            </value>
            <value>
                <fullName>BTO</fullName>
            </value>
            <value>
                <fullName>STO Transfer</fullName>
            </value>
            <value>
                <fullName>TAG External Notification</fullName>
            </value>
            <value>
                <fullName>Chat Threat</fullName>
            </value>
            <value>
                <fullName>Kommunal hurtigtekst</fullName>
            </value>
            <value>
                <fullName>TAG Admin</fullName>
            </value>
            <value>
                <fullName>Besvart med Bob</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Date__c.field-meta.xml
<CustomField>
    <fullName>CRM_Date__c</fullName>
    <description>Date when a record was created or updated</description>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Region__c.field-meta.xml
<CustomField>
    <fullName>CRM_Region__c</fullName>
    <description>Users&#39;s region</description>
    <label>Region</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ReportingData__c/fields/CRM_Value__c.field-meta.xml
<CustomField>
    <fullName>CRM_Value__c</fullName>
    <description>Reporting value in integer</description>
    <label>Value</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserAdoptionService.cls
public with sharing class UserAdoptionService {

    public static void insertReportingDataLastWeek() {

        DateTime periodStart =DateTime.now().addDays(-7);


        List<ReportingData__c> reportingData = getLastLogInByRegion(periodStart);
        insert reportingData;
    }

    @TestVisible
    private static List<ReportingData__c> getLastLogInByRegion(DateTime periodStart) {

        AggregateResult[] usersByRegion = [
                SELECT Region__c, COUNT(ID) Logins
                FROM User
                WHERE LastLoginDate >= :periodStart
                GROUP BY Region__c
        ];

        List<ReportingData__c> reportingData = new List<ReportingData__c>();
        for (AggregateResult ar : usersByRegion) {
            reportingData.add(new ReportingData__c(
                    Name = 'Pålogging',
                    CRM_Region__c = (String) ar.get('Region__c'),
                    CRM_Value__c = (Integer) ar.get('Logins'),
                    CRM_Date__c =Date.today().addDays(-1),
                    CRM_Category__c = 'User Adoption'
            ));
        }
        return reportingData;
    }


}